### ISSUE TITLE
Updates para Frena La Curva Mapa

### ISSUE THREAD

**Issue by RodolfoFerro** [CodeandoMexico/frenalacurvamx#11]
### Descripción

La contribución general consiste en añadir una sección nueva con el diseño que se despliega al final de esta descripción en un nuevo URL `/mapa`. 

La estructura general del sitio y plataformas quedaría como sigue:

![photo_2020-04-08 19 24 30](https://user-images.githubusercontent.com/8453749/78845615-a5329180-79ce-11ea-8b96-f1708c95771d.jpeg)

### Issues

Los updates serán descompuestos en issues para trabajar los distintos bloques:
- [x] [HTML Base + Navbar](https://github.com/CodeandoMexico/frenalacurvamx/issues/13)
- [x] [Sección de header](https://github.com/CodeandoMexico/frenalacurvamx/issues/14)
- [x] [Sección "¿Qué puedo encontrar en el mapa?"](https://github.com/CodeandoMexico/frenalacurvamx/issues/15)
- [x] [Sección "¿Quieres ser parte del equipo de moderación?"](https://github.com/CodeandoMexico/frenalacurvamx/issues/16)
- [x] [Sección de footer](https://github.com/CodeandoMexico/frenalacurvamx/issues/17)

### Diseño

![photo_2020-04-08 20 43 43](https://user-images.githubusercontent.com/8453749/78849395-fd22c580-79d9-11ea-99c1-cdc3de433490.jpeg)
